### ISSUE TITLE
When saving file no extension added

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject-org/papagayo-ng#58] opened 2019-08-04 08:21 UTC
Steps to reproduce:

1. Open Wav file
2. Choose "File" - "Save" from menu
3. In saving dialog enter filename "test" (without extension)
4. Click save.

Result: files is saved as "test", without any extension.

Expected result: it should be saved as "test.pgo".

**Comment by steveway** [comment] 2019-08-13 09:44
That is strange, I just tested this and can't reproduce this. My files do get the .pgo added here.
Tested with the current code on Windows 10.

**Comment by mase76** [comment] 2021-02-06 21:58
I have a different behaviour on Linux. When I don't enter an extension, nothing is saved at all. And there is no error message about a missing extension. Just nothing saved.

**Comment by steveway** [comment] 2021-07-02 08:56
I believe this might be fixed by this: https://github.com/morevnaproject-org/papagayo-ng/pull/88
This commit to be precise: https://github.com/morevnaproject-org/papagayo-ng/pull/88/commits/97395ec29dc09effde9cda0a9cb762e5f711da20

**Closed** 2021-08-13 08:15 UTC
