### ISSUE TITLE
On maximizing the app window, the app crash with segmentation fault.

### ISSUE THREAD

**Issue by dadoprom** [morevnaproject-org/papagayo-ng#74] opened 2020-08-11 22:16 UTC
On maximizing the app window, the app crash with segmentation fault.
Papagayo version: Tested the version with the latest commits.

Terminal output here:
```

dadoprom@185E0F1298C9:~/Stiahnuté/papagayo-ng-master$ python3 papagayo-ng.py
LoadedWaveFormView
/home/dadoprom/Stiahnuté/papagayo-ng-master/rsrc/mouths/1 - Mouth 1 ['FV.png', 'WQ.png', 'O.png', 'etc.png', 'rest.png', 'U.png', 'AI.png', 'L.png', 'MBP.png', 'E.png']
/home/dadoprom/Stiahnuté/papagayo-ng-master/rsrc/mouths/5 - Fleming and Dobbs ['NLTDR.jpg', 'GK.jpg', 'MBP.jpg', 'IY.jpg', 'EHSZ.jpg', 'AA.jpg', 'source.sif', 'SH.jpg', 'O.jpg', 'TH.jpg', 'rest.jpg', 'FV.jpg']
/home/dadoprom/Stiahnuté/papagayo-ng-master/rsrc/mouths/2 - Mouth 2 ['U.jpg', 'MBP.jpg', 'WQ.jpg', 'O.jpg', 'AI.jpg', 'rest.jpg', 'etc.jpg', 'L.jpg', 'FV.jpg', 'E.jpg']
/home/dadoprom/Stiahnuté/papagayo-ng-master/rsrc/mouths/3 - Gary C Martin ['U.jpg', 'MBP.jpg', 'WQ.jpg', 'O.jpg', 'AI.jpg', 'rest.jpg', 'etc.jpg', 'L.jpg', 'FV.jpg', 'E.jpg']
/home/dadoprom/Stiahnuté/papagayo-ng-master/rsrc/mouths/6 - Azia Comics 1 (preston_blair) ['U.jpg', 'MBP.jpg', 'WQ.jpg', 'O.jpg', 'AI.jpg', 'rest.jpg', 'etc.jpg', 'L.jpg', 'FV.jpg', 'E.jpg']
/home/dadoprom/Stiahnuté/papagayo-ng-master/rsrc/mouths/4 - Preston Blair ['U.jpg', 'MBP.jpg', 'WQ.jpg', 'O.jpg', 'AI.jpg', 'rest.jpg', 'etc.jpg', 'L.jpg', 'FV.jpg', 'E.jpg']
/home/dadoprom/Stiahnuté/papagayo-ng-master/rsrc/mouths/7 - Azia Comics 2 (preston_blair) ['U.jpg', 'MBP.jpg', 'WQ.jpg', 'O.jpg', 'AI.jpg', 'rest.jpg', 'etc.jpg', 'L.jpg', 'FV.jpg', 'E.jpg']
/home/dadoprom/Stiahnuté/papagayo-ng-master/rsrc/mouths/8 - Rhubarb ['H.png', 'A.png', 'rest.png', 'F.png', 'B.png', 'C.png', 'E.png', 'D.png', 'G.png']
['AllowNestedDocks', 'AllowTabbedDocks', 'AnimatedDocks', 'DockOption', 'DockOptions', 'DrawChildren', 'DrawWindowBackground', 'ForceTabbedDocks', 'GroupedDragging', 'IgnoreMask', 'PaintDeviceMetric', 'PdmDepth', 'PdmDevicePixelRatio', 'PdmDevicePixelRatioScaled', 'PdmDpiX', 'PdmDpiY', 'PdmHeight', 'PdmHeightMM', 'PdmNumColors', 'PdmPhysicalDpiX', 'PdmPhysicalDpiY', 'PdmWidth', 'PdmWidthMM', 'RenderFlag', 'RenderFlags', 'VerticalTabs', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'acceptDrops', 'accessibleDescription', 'accessibleName', 'actionEvent', 'action_about_papagayo_ng', 'action_copy', 'action_cut', 'action_exit', 'action_help_topics', 'action_open', 'action_paste', 'action_play', 'action_reset_zoom', 'action_save', 'action_save_as', 'action_stop', 'action_undo', 'action_zoom_in', 'action_zoom_out', 'actions', 'activateWindow', 'addAction', 'addActions', 'addDockWidget', 'addToolBar', 'addToolBarBreak', 'add_tag', 'adjustSize', 'apply_fps', 'autoFillBackground', 'backgroundRole', 'backingStore', 'baseSize', 'blockSignals', 'breakdown_button', 'centralWidget', 'central_widget', 'changeEvent', 'childAt', 'childEvent', 'children', 'childrenRect', 'childrenRegion', 'choose_imageset_button', 'clearFocus', 'clearMask', 'close', 'closeEvent', 'colorCount', 'connect', 'connectNotify', 'contentsMargins', 'contentsRect', 'contextMenuEvent', 'contextMenuPolicy', 'corner', 'create', 'createPopupMenu', 'createWinId', 'createWindowContainer', 'current_voice', 'current_voice_page', 'current_voice_page_layout', 'cursor', 'customContextMenuRequested', 'customEvent', 'deleteLater', 'depth', 'destroy', 'destroyed', 'devType', 'devicePixelRatio', 'devicePixelRatioF', 'devicePixelRatioFScale', 'disconnect', 'disconnectNotify', 'dockOptions', 'dockWidgetArea', 'documentMode', 'dragEnterEvent', 'dragLeaveEvent', 'dragMoveEvent', 'dropEvent', 'dumpObjectInfo', 'dumpObjectTree', 'dynamicPropertyNames', 'effectiveWinId', 'emit', 'ensurePolished', 'enterEvent', 'event', 'eventFilter', 'export_button', 'export_combo', 'export_group', 'export_layout', 'find', 'findChild', 'findChildren', 'focusInEvent', 'focusNextChild', 'focusNextPrevChild', 'focusOutEvent', 'focusPolicy', 'focusPreviousChild', 'focusProxy', 'focusWidget', 'font', 'fontInfo', 'fontMetrics', 'foregroundRole', 'fps', 'fps_controls', 'fps_input', 'fps_layout', 'frameGeometry', 'frameSize', 'geometry', 'getContentsMargins', 'grab', 'grabGesture', 'grabKeyboard', 'grabMouse', 'grabShortcut', 'graphicsEffect', 'graphicsProxyWidget', 'hasFocus', 'hasHeightForWidth', 'hasMouseTracking', 'hasTabletTracking', 'height', 'heightForWidth', 'heightMM', 'hide', 'hideEvent', 'horizontalLayout_4', 'horizontal_layout', 'iconSize', 'iconSizeChanged', 'inherits', 'initPainter', 'inputMethodEvent', 'inputMethodHints', 'inputMethodQuery', 'insertAction', 'insertActions', 'insertToolBar', 'insertToolBarBreak', 'installEventFilter', 'internalWinId', 'isActiveWindow', 'isAncestorOf', 'isAnimated', 'isDockNestingEnabled', 'isEnabled', 'isEnabledTo', 'isEnabledToTLW', 'isFullScreen', 'isHidden', 'isLeftToRight', 'isMaximized', 'isMinimized', 'isModal', 'isRightToLeft', 'isSeparator', 'isSignalConnected', 'isTopLevel', 'isVisible', 'isVisibleTo', 'isWidgetType', 'isWindow', 'isWindowModified', 'isWindowType', 'keyPressEvent', 'keyReleaseEvent', 'keyboardGrabber', 'killTimer', 'language_choice', 'layout', 'layoutDirection', 'leaveEvent', 'list_of_tags', 'locale', 'logicalDpiX', 'logicalDpiY', 'lower', 'mapFrom', 'mapFromGlobal', 'mapFromParent', 'mapTo', 'mapToGlobal', 'mapToParent', 'mask', 'maximumHeight', 'maximumSize', 'maximumWidth', 'menuBar', 'menuWidget', 'menu_edit', 'menu_file', 'menu_help', 'menubar', 'metaObject', 'metric', 'minimumHeight', 'minimumSize', 'minimumSizeHint', 'minimumWidth', 'mouseDoubleClickEvent', 'mouseGrabber', 'mouseMoveEvent', 'mousePressEvent', 'mouseReleaseEvent', 'mouth_choice', 'mouth_view', 'mouth_view_layout', 'move', 'moveEvent', 'moveToThread', 'nativeEvent', 'nativeParentWidget', 'nextInFocusChain', 'normalGeometry', 'objectName', 'objectNameChanged', 'overrideWindowFlags', 'overrideWindowState', 'paintEngine', 'paintEvent', 'painters', 'paintingActive', 'palette', 'parent', 'parentWidget', 'parent_tags', 'phoneme_group', 'phoneme_layout', 'phoneme_set', 'physicalDpiX', 'physicalDpiY', 'pos', 'previousInFocusChain', 'property', 'raise_', 'receivers', 'rect', 'redirected', 'registerUserData', 'releaseKeyboard', 'releaseMouse', 'releaseShortcut', 'reload_dict_button', 'removeAction', 'removeDockWidget', 'removeEventFilter', 'removeToolBar', 'removeToolBarBreak', 'remove_tag', 'render', 'repaint', 'resize', 'resizeDocks', 'resizeEvent', 'restoreDockWidget', 'restoreGeometry', 'restoreState', 'saveGeometry', 'saveState', 'screen', 'scroll', 'sender', 'senderSignalIndex', 'setAcceptDrops', 'setAccessibleDescription', 'setAccessibleName', 'setAnimated', 'setAttribute', 'setAutoFillBackground', 'setBackgroundRole', 'setBaseSize', 'setCentralWidget', 'setContentsMargins', 'setContextMenuPolicy', 'setCorner', 'setCursor', 'setDisabled', 'setDockNestingEnabled', 'setDockOptions', 'setDocumentMode', 'setEnabled', 'setFixedHeight', 'setFixedSize', 'setFixedWidth', 'setFocus', 'setFocusPolicy', 'setFocusProxy', 'setFont', 'setForegroundRole', 'setGeometry', 'setGraphicsEffect', 'setHidden', 'setIconSize', 'setInputMethodHints', 'setLayout', 'setLayoutDirection', 'setLocale', 'setMask', 'setMaximumHeight', 'setMaximumSize', 'setMaximumWidth', 'setMenuBar', 'setMenuWidget', 'setMinimumHeight', 'setMinimumSize', 'setMinimumWidth', 'setMouseTracking', 'setObjectName', 'setPalette', 'setParent', 'setProperty', 'setShortcutAutoRepeat', 'setShortcutEnabled', 'setSizeIncrement', 'setSizePolicy', 'setStatusBar', 'setStatusTip', 'setStyle', 'setStyleSheet', 'setTabOrder', 'setTabPosition', 'setTabShape', 'setTabletTracking', 'setToolButtonStyle', 'setToolTip', 'setToolTipDuration', 'setUnifiedTitleAndToolBarOnMac', 'setUpdatesEnabled', 'setVisible', 'setWhatsThis', 'setWindowFilePath', 'setWindowFlag', 'setWindowFlags', 'setWindowIcon', 'setWindowIconText', 'setWindowModality', 'setWindowModified', 'setWindowOpacity', 'setWindowRole', 'setWindowState', 'setWindowTitle', 'sharedPainter', 'show', 'showEvent', 'showFullScreen', 'showMaximized', 'showMinimized', 'showNormal', 'signalsBlocked', 'size', 'sizeHint', 'sizeIncrement', 'sizePolicy', 'splitDockWidget', 'spread_out', 'stackUnder', 'startTimer', 'staticMetaObject', 'statusBar', 'statusTip', 'statusbar', 'style', 'styleSheet', 'tabPosition', 'tabShape', 'tabifiedDockWidgetActivated', 'tabifiedDockWidgets', 'tabifyDockWidget', 'tabletEvent', 'tag_entry', 'tag_list_buttons', 'tag_list_group', 'tag_splitter', 'takeCentralWidget', 'testAttribute', 'text_edit', 'text_input_group', 'thread', 'timerEvent', 'toolBarArea', 'toolBarBreak', 'toolButtonStyle', 'toolButtonStyleChanged', 'toolTip', 'toolTipDuration', 'toolbar', 'topLevelWidget', 'tr', 'underMouse', 'ungrabGesture', 'unifiedTitleAndToolBarOnMac', 'unsetCursor', 'unsetLayoutDirection', 'unsetLocale', 'update', 'updateGeometry', 'updateMicroFocus', 'updatesEnabled', 'verticalLayout', 'verticalLayout_2', 'verticalLayout_3', 'verticalLayout_5', 'vertical_layout_left', 'vertical_layout_left_1', 'vertical_layout_right', 'visibleRegion', 'voice_name', 'voice_name_input', 'voice_name_layout', 'volume_slider', 'waveform_view', 'whatsThis', 'wheelEvent', 'width', 'widthMM', 'winId', 'window', 'windowFilePath', 'windowFlags', 'windowHandle', 'windowIcon', 'windowIconChanged', 'windowIconText', 'windowIconTextChanged', 'windowModality', 'windowOpacity', 'windowRole', 'windowState', 'windowTitle', 'windowTitleChanged', 'windowType', 'x', 'y']
['1 - Mouth 1', '2 - Mouth 2', '3 - Gary C Martin', '4 - Preston Blair', '5 - Fleming and Dobbs', '6 - Azia Comics 1 (preston_blair)', '7 - Azia Comics 2 (preston_blair)', '8 - Rhubarb']
import phonemes_preston_blair as phonemeset
QPropertyAnimation::updateState (geometry, QWidget, central_widget): starting an animation without end value
Segmentation fault
```
-------

Operating System: KDE neon 5.19
KDE Plasma Version: 5.19.4
KDE Frameworks Version: 5.72.0
Qt Version: 5.14.2
Kernel Version: 5.3.0-28-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i3-5010U CPU @ 2.10GHz
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 5500
------
And I have compositor effects turned to off.

**Comment by steveway** [comment] 2020-08-12 04:44
Mhh, I can't reproduce this crash here on Windows 10 nor in a Ubuntu 20.04 VM.
Is this reproducible or does this only happen sometimes?
A Segmentation Fault normally happens from the underlying libraries, so in this case QT is likely the culprit.
But without being able to reproduce this I can't even begin to analyse if we can do something against it.

**Comment by dadoprom** [comment] 2020-08-12 19:26
> Is this reproducible or does this only happen sometimes?
Yes, It happens almost all the time... sometimes you can maximize once and then on demaximize there the crash happens (segmentation fault)

**Comment by steveway** [comment] 2020-08-13 08:03
That is strange, are you sure that you are using the current commit?
I can't replicate this on my Ubuntu VM at all, it nicely maximizes and de-maximizes here.
The cause could be a multitude of things, maybe the graphics-card/driver combo is problematic or the window manager does strange things.
Here on a standard Ubuntu 20.04 I can't replicate this.

**Comment by dadoprom** [comment] 2020-08-13 15:01
perhaps try it with KDE neon 5.19 (18.04) in VM

**Comment by steveway** [comment] 2020-08-17 12:41
Mhh, while experimenting with this using the Linux on Windows solution of Windows 10 I can get it to crash when resizing.
Interestingly it does not crash on maximize.
Also using the sides or corners resizes without crash.
But if I use the QSizeGrip on the bottom right to resize then it crashes.
And, I think I found the line which causes this by using the -m trace option of python...
In the WaveformViewRewrite, if I uncomment the QtCore.QCoreApplication.processEvents() line at the end of the resizeEvent then this does not seem to crash anymore.
I'm not sure if anything else is broken by this.
But this also seems to fix the sporadic crashes at startup mentioned in #77

**Comment by steveway** [comment] 2020-08-17 14:58
After some more research this seems to be related to this:
https://bugreports.qt.io/browse/QTBUG-31524
It looks like calling processevents from inside an event is not recommended.

**Comment by steveway** [comment] 2021-07-02 08:50
Should be fixed in this: https://github.com/morevnaproject-org/papagayo-ng/pull/94

**Closed by steveway** 2021-07-02 08:50 UTC
