### ISSUE TITLE
FPS widget doesn't works correctly

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject-org/papagayo-ng#57] opened 2019-08-04 08:14 UTC
Changing FPS doesn't affects waveform view. Currently it changes speed of cursor movement while playback.

The expected behaviour: it should stretch waveform accordingly to new fps (this is how it was working in wx-based version) - https://www.youtube.com/watch?v=STHLs4v7RA8

**Comment by steveway** [comment] 2019-08-13 09:54
Thanks for the video.
Let's see: 
- The waveform itself resizes depending on the change.
- So if we halve the framerate the waveform also halves in width.
- The content does not get touched.
- The markings in the background also stay visually the same which works out correctly if the waveform is changed correctly.
- The playbackmarker needs to change it's speed accordingly, since it's position is calculated based on the current playback position that shouldn't be too difficult.

Then for QT we need to take some care when doing that that the scene is resized correctly and the scrollbar is working.
And maybe some more things I did not yet think of.

**Comment by steveway** [comment] 2019-08-13 10:55
Ok, I think this might already be correct in my current commit here:
https://github.com/steveway/papagayo-ng/commit/9ae85d2357b4b63bd41b20b477990986caf270d0
It looks like it behaves mostly the same, further testing is recommended.
(Especially someone should test how this behaves if the FPS get's changed by unusual values instead of simply doubling and halving them.)

**Comment by Hunanbean** [comment] 2020-08-14 19:57
I am having issues with waveform display truncating before the end of the actual audio, making it impossible to, well, use this as it is. this is with the current code base 08/14/2020
changing the fps to 60 is initially what seemed to cause the problem. switching back to 24, closing and reopening, trying to drag further than the waveform display, resizing.. none of this fixes it. also, when i open a previously opened .wav, it seems to remember the last FPS i had it set at. I am at a loss. this happens whether i drag the .wav in, or use the file menu dialog. so far, i have just been testing with the three original .wav files that came with the original papagayo.

Thank you, and good luck

**Comment by steveway** [comment] 2020-08-17 14:37
Mhh, this seems to work as expected here.
I opened a project and changed the FPS from 24 to 60 and the waveform increased in size as expected.
When I open a different file or change the FPS it changes to that correctly too.
Could you make a video of the steps you used to reproduce this?

**Comment by Hunanbean** [comment] 2020-08-17 21:06
Turns out, if after i switch back and forth between the FPS options, i
resize the window, it redraws the full waveform and allows left/right
scrolling again.

I could perhaps make a video, but i do not know where a good spot to upload
it would be. i would prefer not to use youtube for this purpose

**Comment by steveway** [comment] 2021-07-02 08:54
Are you sure this is still broken with the current version?
I can't reproduce it with: https://github.com/morevnaproject-org/papagayo-ng/pull/94

**Comment by Hunanbean** [comment] 2021-07-02 21:44
I have not tried it with the version released in the past few hours, but when i tried the first iteration of the allosaurus inclusion, it was still present. that was just days ago. I will test he latest version as soon as i can, and report back here.

**Comment by Hunanbean** [comment] 2021-07-02 22:19
It appears to be working fine in the current Allosaurus version.

Thank you

p.s. I do not have the option to close this issue

**Comment by steveway** [comment] 2021-07-03 14:31
Can you make a video or send a file to reproduce?
With my test files I can't reproduce this.

**Comment by Hunanbean** [comment] 2021-07-03 17:32
This occurs on the first file dragged in after opening Papagayo-NG. It turns out i do not actually have to change the fps, i just need to hit reset zoom. After pressing reset zoom, any subsequent audio files dragged in seem to zoom properly without needing to do that again. I am not sure if this is expected behavior or not. I am trying to get OBS setup now, in case a video is still needed

**Comment by steveway** [comment] 2021-08-13 08:54
I can't reproduce this with the current version, this seems to be fixed for now.

**Closed by steveway** 2021-08-13 08:54 UTC

**Comment by Hunanbean** [comment] 2021-08-15 09:43
My apologies. I lost track of this issue. Uploading a video demonstartion now.

https://user-images.githubusercontent.com/52123900/129474298-18ee7938-9337-4d22-8a8b-da4b91b4a215.mp4

**Comment by steveway** [comment] 2021-08-16 09:44
Can you test my cli_test branch?
https://github.com/steveway/papagayo-ng/tree/cli_test
I just added a change which might help.
It seems that non-24 FPS settings load correctly now.
The Waveform still disappears sometimes when zooming in and out, not sure why that happens yet, but a small resize fixes that.
I'm really not sure why it sometimes disappears, all the data of the Polygon seems to be correct, it just doesn't want to draw it, at least a resize fixes that.
I wanted to create a chunking system which splits the waveform into several pieces for performance reasons anyway, so if I start creating that I'll likely find out more about that problem.

**Comment by Hunanbean** [comment] 2021-08-16 10:30
In the CLI branch, i am seeing some of the old issues back. Such as, the volume level does not change when moving the slider while the audio is playing. The drag and drop is not currently functioning. The issue with the window requiring a resize are present. But this may be expected at this point.
On the plus side, It seems to load must faster (Just observing, have not timed it). And the 60fps file view is working properly and going all the way to the end of the file without have to zoom!

**Comment by Hunanbean** [comment] 2021-08-16 10:32
To note, it is still requiring silence at the end of the audio files i have tested

**Comment by steveway** [comment] 2021-08-16 11:02
I've switched from SoundPlayerNew to SoundPlayer on this branch because the other one fails without a GUI and still needs adjusting for a purce CLI run.
There has been no change to drag and drop.
The changes are mostly some CLI parsing, the SoundPlayer temporarily and this one which seems to fix loading non 24FPS files.
So it should behave mostly the same as the regular version.

**Comment by Hunanbean** [comment] 2021-08-16 11:19
Ok, I see what happened. I had run the program from an admin command line. It does not allow drag and drop while elevated, it seems.

**Comment by steveway** [comment] 2021-08-16 12:08
Oh, I see, yeah that is not recommended.
I changed some logic so it should now use the same Playback as before which allows for changes while playing on Windows.
And for CLI usage it should now always use SoundPlayer.py .
So the only thing seems to be the waveform sometimes disappearing, but as far as I know this also happens in the current normal version.
